AWSTemplateFormatVersion: "2010-09-09"
Description: Debugging template for S3 bucket issues.

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

Outputs:
  FrontendURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: "Public URL for the photo album frontend."