AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to provision resources for a photo album web application.

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-photo-album-bucket"
      ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: "index.html"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
    DeletionPolicy: Retain

  # Frontend Bucket Policy
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Resource: !Join ["", ["arn:aws:s3:::", !Ref FrontendBucket, "/*"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${AWS::StackName}-frontend-photo-album-bucket/*"

Outputs:
  FrontendURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: "Public URL for the photo album frontend."